apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: leaderboard
  name: leaderboard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: leaderboard
  template:
    metadata:
      labels:
        app: leaderboard
    spec:
      containers:
      - image: r.deso.tech/pacman/pacman-leaderboard
        name: leaderboard
        env:
          - name: AWS_REGION
            value: eu-south-1
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                key: aws-access-key-id
                name: aws-users-secret
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                key: aws-secret-access-key
                name: aws-users-secret
